on:
  push

jobs:
  unit-tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ruby: [ '2.6', '2.7', '3.0' ]
    name: Vagrant unit tests on Ruby ${{ matrix.ruby }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          architecture: 'x64'
      - name: Run Tests
        run: .ci/test.sh
